schema_version = "1.0.0"

id = "blender_collada_support"
version = "1.0.2"
name = "Blender Collada Support"
tagline = "COLLADA (.dae) import and export for Blender 5"
maintainer = "Blender Collade Support"
type = "add-on"

website = "https://github.com/KimsFerdy/blender_pycollada_importexport"
tags = ["Import-Export", "Pipeline"]

blender_version_min = "5.0.0"

license = ["SPDX:GPL-2.0-or-later"]

wheels = [
    "./wheels/pycollada-0.9.1-py3-none-any.whl",
    "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
    "./wheels/six-1.17.0-py2.py3-none-any.whl",
]

[permissions]
network = "Optionally reinstall or upgrade pycollada via pip"
files = "Read/write COLLADA .dae/.zae/.kmz/.zip files and textures"
