schema_version = "1.0.0"

id = "collada_support"
version = "1.1.3"
name = "Collada Support"
tagline = "COLLADA (.dae) import and export for Blender 5"
maintainer = "Collada Support for Blender 5.X"
type = "add-on"

website = "https://github.com/Dank-Heehaw/Collada-Support-for-Blender-5.X"
tags = ["Import-Export", "Pipeline"]

blender_version_min = "5.0.0"

license = ["SPDX:GPL-3.0-or-later"]

wheels = [
    "./wheels/pycollada-0.9.1-py3-none-any.whl",
    "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
    "./wheels/six-1.17.0-py2.py3-none-any.whl",
]

[permissions]
files = "Read/write COLLADA .dae/.zae/.kmz/.zip files and textures"
